name: Deploy React App to Vercel

on: 
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install Dependencies
        run: npm install          

      - name: Build React App
        run: npm run build
                                      

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Deploy to Vercel
        run: vercel --token=${{ secrets.VERCEL_TOKEN }} --yes --prod
